version: '3.1'

services:
  api:
    build: .
    container_name: api
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
  db:
    image: mongo
    volumes:
      - ./mongo_data:/data/db
    container_name: mongodb
    ports:
      - '${DB_PORT}:${DB_PORT}'
    env_file:
      - .env